services:
  rdfm-server:
    image: antmicro/rdfm-server:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --cacert /certs/CA.crt --fail https://rdfm-server:5000/api/v1/packages || exit 1" ]
      interval: 30s
      retries: 1
      start_period: 10s
      timeout: 5s
    ports:
      - '1234:1234'
      - '5000:5000'
    networks:
      - rdfm
    env_file: "secrets.env"
    environment:
      RDFM_DB_CONNSTRING: sqlite:////database/development.db
      RDFM_HOSTNAME: rdfm-server
      RDFM_API_PORT: 5000
      RDFM_DEVICE_PORT: 1234
      RDFM_DISABLE_API_AUTH: 1
      RDFM_LOCAL_PACKAGE_DIR: /packages/
      RDFM_WSGI_SERVER: werkzeug
      RDFM_SERVER_CERT: /certs/SERVER.crt
      RDFM_SERVER_KEY: /certs/SERVER.key

    volumes:
      - db:/database/
      - pkgs:/packages/
      - ./server:/certs

  rdfm-linux-client:
    image: antmicro/rdfm-linux-demo-client-stress:latest
    restart: unless-stopped
    networks:
      - rdfm
    depends_on:
      rdfm-server:
        condition: service_healthy
    environment:
      RDFM_CLIENT_DEVTYPE: x86_64
      RDFM_CLIENT_SERVER_URL: https://rdfm-server:5000/
      RDFM_CLIENT_SERVER_CERT: /var/lib/rdfm/CA.crt
      RDFM_TELEMETRY_BOOTSTRAP_SERVERS: broker:9093
      RDFM_TELEMETRY_LOG_LEVEL: "INFO"
      RDFM_TELEMETRY_ENABLE: true

    volumes:
      - ./server:/var/lib/rdfm/

volumes:
  db:
  pkgs:
  keycloak:

networks:
  rdfm:
