image: $CI_REGISTRY_IMAGE:rdfm-ci-base-bookworm

.common_only: &common_only
  only:
    - main
    - merge_requests

variables:
  SSL_CERT_DIR: "certs"
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  GOROOT: ""
  SCALENODE_CPU: 2
  SCALENODE_RAM: 2048
  SCALENODE_DISK: 20

.build-base:
  variables:
    JWT_SECRET: testsecret123123123
    POSTGRES_MAJOR_VERSION: 15
  before_script:
    - python -V
    - (apt update &&
        apt-get -y install make netcat-openbsd openssl telnet uuid-runtime xxd postgresql-$POSTGRES_MAJOR_VERSION postgresql-contrib cmake &&
        service postgresql start &&
        ln -s /usr/lib/postgresql/$POSTGRES_MAJOR_VERSION/bin/initdb /bin/initdb &&
        ln -s /usr/lib/postgresql/$POSTGRES_MAJOR_VERSION/bin/postgres /bin/postgres)
    - git clone https://github.com/antmicro/go-xdelta xdelta
    - cd xdelta
    - cmake -B build/ -DCGO_INTEGRATION=ON -DENCODER=ON
    - cmake --build build/
    - cmake --install build/
    - cd ../
    - (cd server && poetry build && poetry install)
    - (cd manager && poetry build && poetry install)
    - server/tests/certgen.sh certs IP.1:127.0.0.1 DEVICE no

.build:
  <<: *common_only
  extends: .build-base

.install-xdelta:
  before_script:
    - apt-get update
    - apt-get install -y cmake
    - git clone https://github.com/antmicro/go-xdelta xdelta
    - cd xdelta
    - cmake -B build/ -DENCODER=ON -DCGO_INTEGRATION=ON
    - cmake --build build/
    - cmake --install build/
    - cd ../

stages:
  - docs-build
  - docs-deploy
  - build
  - static-checks
  - local-tests

python-pycodestyle-check:
  extends: .build
  stage: static-checks
  script:
    - (cd server && poetry run test-pycodestyle)
    - (cd manager && poetry run test-pycodestyle)

python-mypy-check:
  extends: .build
  stage: static-checks
  script:
    - (cd server && poetry run test-mypy)
    - (cd manager && poetry run test-mypy)
  allow_failure: true

test-package-api:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-packages.py

test-group-api:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-groups.py

test-server-update-policies:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-update-policies.py --sqlite
    - poetry run pytest tests/test-update-policies.py --postgres

test-server-update-resolver:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-update-resolver.py

test-server-update-api:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-update-checker.py --sqlite
    - poetry run pytest tests/test-update-checker.py --postgres

test-server-device-auth-api:
  extends: .build
  stage: local-tests
  variables:
    SCALENODE_RAM: 4096
  script:
    - cd server
    - poetry run pytest tests/test-server-auth.py --sqlite
    - poetry run pytest tests/test-server-auth.py --postgres

test-server-s3-storage:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-server-s3-storage.py

test-server-management-auth:
  extends: .build
  stage: local-tests
  variables:
    SCALENODE_RAM: 4096
  script:
    - cd server
    - poetry run pytest tests/test-server-management-auth.py --sqlite
    - poetry run pytest tests/test-server-management-auth.py --postgres

test-package-upload-auth:
  extends: .build
  stage: local-tests
  variables:
    SCALENODE_RAM: 4096
  script:
    - cd server
    - poetry run pytest tests/test-package-upload-auth.py --sqlite
    - poetry run pytest tests/test-package-upload-auth.py --postgres

test-server-route-correctness:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-server-route-correctness.py

test-server-websocket:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-server-ws.py --sqlite
    - poetry run pytest tests/test-server-ws.py --postgres

test-manager:
  extends: .build
  stage: local-tests
  variables:
    SCALENODE_RAM: 4096
  script:
    - cd server
    - poetry run pytest tests/test-manager.py --sqlite
    - poetry run pytest tests/test-manager.py --postgres

test-server-stress:
  extends: .build
  stage: local-tests
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 32768
  script:
    - cd server
    - poetry run pytest tests/test-stress.py -vs
  artifacts:
    paths:
      - server/tests/logs/*
    when: always

test-server-logs:
  extends: .build
  stage: local-tests
  script:
    - cd server
    - poetry run pytest tests/test-server-logs.py --sqlite
    - poetry run pytest tests/test-server-logs.py --postgres

# ===== rdfm-client ===== #

build-rdfm-client:
  stage: build
  before_script:
    # Currently CI ships Go 1.19, while the client needs 1.20+
    - wget --quiet -O - "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz" | tar xz
  script:
    - export PATH=`pwd`/go/bin:$PATH
    - cd devices/linux-client
    - make

build-rdfm-logging-tool:
  stage: build
  script:
    - cd tools/loggers
    - make

test-rdfm-client:
  stage: local-tests
  <<: *common_only
  dependencies:
    - build-rdfm-artifact
  script:
    # Install rdfm-artifact, which is required for the tests
    - mv tools/rdfm-artifact/rdfm-artifact /usr/bin/
    # Currently CI ships Go 1.19, while the client needs 1.20+
    - wget --quiet -O - "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz" | tar xz
    - export PATH=`pwd`/go/bin:$PATH
    - cd devices/linux-client
    - make test

test-rdfm-client-docker:
  stage: local-tests
  <<: *common_only
  dependencies:
    - build-rdfm-artifact
  before_script:
    # Currently CI ships Go 1.19, while the client needs 1.20+
    - wget --quiet -O - "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz" | tar xz
  script:
    - export PATH=$HOME/go/bin/:$PATH
    - export PATH=`pwd`/go/bin:$PATH
    # Install rdfm-artifact, which is required for the tests
    - mv tools/rdfm-artifact/rdfm-artifact /usr/bin/
    # The tests are running in a Docker container, install and set up
    # the Docker daemon
    - cd devices/linux-client
    - apt update
    - apt -qq -y --no-install-recommends install docker.io cgroupfs-mount crun fuse-overlayfs pigz ca-certificates
    - cgroupfs-mount
    - ../../common/docker/start-docker.sh
    # HACK: For CI runs, we have to replace the -it flag in docker run
    #       as this is not a real terminal.
    # HACK: We also comment out git invocations, as only a subfolder is mounted
    #       in the container, which would cause that call to fail. This is fine,
    #       as the invocation is only required when container UID != source UID
    #       (i.e, not in CI runs, where we run everything as root).
    - sed -i "s/\-it//g" ./scripts/test-docker/test-artifact-info.sh
    - sed -i "s/git/#git/g" ./scripts/test-docker/data/check-artifact-info.sh
    - sed -i "s/\-it//g" ./scripts/test-docker/test-deltas.sh
    - sed -i "s/git/#git/g" ./scripts/test-docker/data/check-delta-patching.sh
    - sed -i "s/\-it//g" ./scripts/test-docker/test-delta-over-http.sh
    # Run rdfm-client Docker tests
    - ./scripts/test-docker/test-artifact-info.sh
    - cd scripts/test-docker/
    - ./make-delta-samples.sh
    - cd ../../
    - ./scripts/test-docker/test-deltas.sh
    - ./scripts/test-docker/test-delta-over-http.sh

# ===== rdfm-mcumgr-client ===== #

build-mcumgr-client:
  stage: build
  before_script:
    # Currently CI ships Go 1.19, while the client needs 1.22+
    - wget --quiet -O - "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz" | tar xz
  script:
    - export PATH=`pwd`/go/bin:$PATH
    - make -C devices/mcumgr-client
  artifacts:
    expire_in: 1 day
    paths:
      - devices/mcumgr-client/rdfm-mcumgr-client

build-mcumgr-test-samples:
  variables:
    SCALENODE_CPU: 4
    SCALENODE_RAM: 8192
    ZEPHYR_WORKSPACE: $CI_PROJECT_DIR/zephyr
    ZEPHYR_BASE: $CI_PROJECT_DIR/zephyr/zephyr
    ZEPHYR_SDK_INSTALL_DIR: $CI_PROJECT_DIR/zephyr/sdk
  <<: *common_only
  stage: build
  before_script:
    - apt update
    - apt -qqy --no-install-recommends install cmake device-tree-compiler ninja-build
  script:
    - ./devices/mcumgr-client/tests/build/build_samples.sh
    - ls -la ./devices/mcumgr-client/tests/out/
  artifacts:
    expire_in: 1 day
    paths:
      - devices/mcumgr-client/tests/out

test-mcumgr-client:
  variables:
    SCALENODE_CPU: 4
    SCALENODE_RAM: 6144
    SCALENODE_DISK: 10
  <<: *common_only
  dependencies:
    - build-mcumgr-client
    - build-mcumgr-test-samples
    - build-rdfm-artifact
  stage: local-tests
  script:
    - set -eo pipefail
    - apt update && apt -qqy --no-install-recommends install iproute2 git-lfs >/dev/null
    # NOTE: Currently Renode is tracked using LFS since we're using a custom
    #       build with support for both STM32F764 and NRF52840 flash controllers.
    #       If they get added into main, this can be replaced with official release
    #       `wget --quiet https://builds.renode.io/renode_1.X.Y_amd64.deb`
    - git lfs pull && apt -qqy --no-install-recommends install ./devices/mcumgr-client/tests/prebuilt/renode*.deb >/dev/null
    - mv tools/rdfm-artifact/rdfm-artifact /usr/bin/
    - mv devices/mcumgr-client/rdfm-mcumgr-client /usr/bin/
    - pushd server && pip3 install -e . && popd
    - pushd manager && pip3 install -e . && popd
    - cd devices/mcumgr-client
    # Run the test
    - ./tests/end2end/test.sh

# ===== rdfm-artifact ===== #

build-rdfm-artifact:
  stage: build
  extends: .install-xdelta
  script:
    - export PATH=$HOME/go/bin/:$PATH
    - cd tools/rdfm-artifact
    - make
  artifacts:
    paths:
      - tools/rdfm-artifact/rdfm-artifact

test-rdfm-artifact:
  <<: *common_only
  stage: local-tests
  extends: .install-xdelta
  script:
    - export PATH=$HOME/go/bin/:$PATH
    - cd tools/rdfm-artifact
    - make test

# ===== rdfm-frontend ===== #

build-rdfm-frontend:
  image: node:20
  stage: static-checks
  <<: *common_only
  script:
    - cd frontend
    - npm install
    - npm run format-check
    - npm run build
  artifacts:
    paths:
      - frontend/dist

# ===== documentation ===== #

docs-build:
  stage: docs-build
  <<: *common_only
  before_script:
    # Disable venvs and just install everything globally
    # The server module must be accessible by Sphinx to
    # properly autogenerate API documentation
    - poetry config virtualenvs.create false
    # Install doc building requirements
    - pip3 install -r documentation/requirements.txt
    # Build and install the server
    - (cd server/ && poetry build --verbose && poetry install --verbose && pip3 install --verbose -e .)
  script:
    - cd documentation/
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    # Make sure the docs archive lands in the root of the repository
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - documentation/build
      - $CI_DOCS_ARCHIVE

docs-deploy:
  variables:
    GIT_STRATEGY: none
  <<: *common_only
  dependencies:
    - docs-build
  stage: docs-deploy
  tags: ["docs"]
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
