# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n\x03log\x12\r\n\x05\x65ntry\x18\x01 \x01(\t\x12\x12\n\ndevice_mac\x18\x02 \x01(\t\x12/\n\x0b\x64\x65vice_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\nZ\x08./protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./protos'
  _LOG._serialized_start=54
  _LOG._serialized_end=143
# @@protoc_insertion_point(module_scope)
