"""Permissions based on name

Revision ID: 8
Revises: 7
Create Date: 2024-11-14 12:43:27.073314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8'
down_revision: Union[str, None] = '7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'resource_id', existing_type=sa.Integer(), nullable=True)
    op.add_column('permissions', sa.Column('resource_name', sa.String(), nullable=True))
    op.create_check_constraint(
        "at_least_one_not_null",
        "permissions",
        "resource_id IS NOT NULL OR resource_name IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'resource_id', existing_type=sa.Integer(), nullable=True)
    op.drop_column('permissions', 'resource_name')
    op.drop_constraint(
        "at_least_one_not_null",
        "permissions",
        type_="check"
    )
    # ### end Alembic commands ###
