FROM debian:trixie

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get -qq -y update && \
    apt-get -qq -y install --no-install-recommends \
	texlive-full \
	texinfo \
	make \
	python3 \
	python3-dev \
	python3-pip \
	python3-poetry \
	libpq-dev \
	build-essential \
	&& \
	apt-get autoclean && \
        apt-get clean && \
        apt-get -y autoremove && \
        rm -rf /var/lib/apt/lists/*
